
name: yorokobi
version: git
summary: Automatic PostgreSQL backups for web apps.
description: |
  The agent is a system service that performs backups, encrypt and 
  transfer them to Yorokobi backup servers.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  yorokobi:
    command: yorokobi

parts:
  yorokobi:
    plugin: python
    python-version: python3
    python-packages:
      - psycopg2-binary
      - click
      - pyzmq
      - schedule
      - inquirer
      - requests
    stage-packages:
      - build-essential
      - devscripts
      - libpq-dev
      - fakeroot
      - python3-setuptools
    source: .
  remofile:
    plugin: python
    source: https://github.com/yorokobicom/remofile.git
