name: yorokobi
base: core18
version: git
summary: Automatic PostgreSQL backups for web apps.
description: |
  The agent is a system service that performs backups, encrypt and
  transfer them to Yorokobi backup servers.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  yorokobi:
    command: yorokobi
  daemon:
    command: yorokobid
    daemon: simple
    restart-condition: always

parts:
  yorokobi:
    plugin: python
    python-packages:
      - psycopg2-binary
      - click
      - pyzmq
      - schedule
      - inquirer
      - pexpect
      - setuptools
      - requests
      - pexpect
      - remofile
    build-packages:
      - libpq-dev
      - libzmq3-dev
    source: .

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
