name: yorokobi
base: core18
version: git
summary: Automatic PostgreSQL backups for web apps.
description: |
  The agent is a system service that performs backups, encrypt and
  transfer them to Yorokobi backup servers.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  yorokobi:
    command: yorokobi
    plugs: 
      - network

  daemon:
    command: yorokobid
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind

parts:
  yorokobi:
    plugin: python
    python-packages:
      - psycopg2-binary
      - click
      - pyzmq
      - schedule
      - inquirer
      - pexpect
      - setuptools
      - requests
      - remofile
    build-packages:
      - libpq-dev
      - libzmq3-dev
    stage-packages:
      - python3
      - python3-pip
      - perl
      - perl-base
      - postgresql-client-10
    source: .      

layout:
  /usr/lib/postgresql/10/bin:
    bind: $SNAP/usr/lib/postgresql/10/bin
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/x86_64-linux-gnu/perl-base:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl-base

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
